---
- name: Install application on VMs
  hosts: tag_app=webapp
  become: yes

  tasks:
    - name: update Oracle Linux
      yum:
        name: '*'
        state: latest
      when: ansible_facts['distribution'] == "OracleLinux"

    - name: install "{{ utilities }}" on Oracle Linux
      yum:
        name: "{{ utilities }}"
        state: latest
      when: ansible_facts['distribution'] == "OracleLinux"

    - name: install "{{ utilities }}" on Ubuntu
      ansible.builtin.apt:
        name: "{{ utilities }}"
        state: latest
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: install "{{ services }}" on Oracle Linux
      yum:
        name: "{{ services }}"
        state: latest
      when: ansible_facts['distribution'] == "OracleLinux"
 
    - name: install "{{ services }}" on Ubuntu
      ansible.builtin.apt:
        name: "{{ services }}"
        state: latest
        update_cache: yes
      when: ansible_facts['distribution'] == "Ubuntu"    

    - name: enable all the services on Ubuntu
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items: "{{ services }}"
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: enable all the services on Oracle Linux
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items: "{{ services }}"
      when: ansible_facts['distribution'] == "OracleLinux"
    
    - name: enable access to ports defined on Ubuntu
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      with_items: "{{ ports }}"
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: enable access to ports defined on Oracle Linux
      ansible.posix.firewalld:
        zone: public
        port: "{{ item }}"
        permanent: yes
        state: enabled
      with_items: "{{ ports }}"
      when: ansible_facts['distribution'] == "OracleLinux"
