---
- name: Install application on VMs
  hosts: tag_app=webapp
  become: yes
  vars_files:
    - "config_file_{{ ansible_facts['distribution'] }}.yml"

  tasks:
    - name: install "{{ utilities }}" on Oracle Linux
      ansible.builtin.yum:
        name: "{{ utilities }}"
        state: latest
        update_cache: yes
      when: ansible_facts['distribution'] == "CentOS"

    - name: install "{{ utilities }}" on Ubuntu
      ansible.builtin.apt:
        name: "{{ utilities }}"
        state: latest
        update_cache: yes
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: install "{{ services }}" on Oracle Linux
      ansible.builtin.yum:
        name: "{{ services }}"
        state: latest
        update_cache: yes
      when: ansible_facts['distribution'] == "CentOS"
 
    - name: install "{{ services }}" on Ubuntu
      ansible.builtin.apt:
        name: "{{ services }}"
        state: latest
        update_cache: yes
      when: ansible_facts['distribution'] == "Ubuntu"    

    - name: enable all the services on Ubuntu
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items: "{{ services }}"
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: enable all the services on Oracle Linux
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items: "{{ services }}"
      when: ansible_facts['distribution'] == "CentOS"
    
    - name: enable access to ports defined on Ubuntu
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      with_items: "{{ ports }}"
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: enable access to ports defined on Oracle Linux
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        jump: ACCEPT
      with_items: "{{ ports }}"
      when: ansible_facts['distribution'] == "CentOS"
